### ISSUE TITLE
Move to Vaadin 23 fails spectactularly

### ISSUE THREAD

**Issue by higgsja** [appreciated/apexcharts-flow#157] opened 2022-12-15 17:09 UTC
Likely something simple as I have not had issues from Vaadin 14->20>21>22. Vaadin made some big changes to v23 so maybe just a config issue. As it starts with an error on Vite, I'm looking into that as well ...

Upon compiling my app, which was fine with Vaadin 22.0.11, I get a large batch of errors about ApexCharts. See attached file.

[hold.txt](https://github.com/appreciated/apexcharts-flow/files/10239147/hold.txt)

**Desktop (please complete the following information):**
 - OS: Linux
 - Chrome

**Comment by TFyre** [comment] 2022-12-15 17:27
Looks duplicate of #155 

Please compile current master and confirm :)

**Comment by higgsja** [comment] 2022-12-15 17:47
Impressive response time. I suspected I might not be alone.

For the moment I took the easy route of going back to Vaadin 23.2.11 
based on the comments from others.

I looked through the issues but did not spot the 155 you referenced; 
thanks for that.

a

--


Thanks!
West Point 1976 H-3
	Join us! <https://hlh-tx.com> 	*Mission:* To measurably improve 
investor performance

"We enjoy the comfort of opinion without the discomfort of thought." -- 
J.F. Kennedy

**Comment by higgsja** [comment] 2022-12-16 12:46
Ok, actually ended up with:
Java 17
Vaadin: 23.2.6
Spring 2.5.14
Apex 23.0.0

**Comment by WilliamFreau** [comment] 2022-12-21 14:25
Hi,

When do yo plan to release the fixed version for Vaadin 23.3.x?

Best regards

**Comment by WilliamFreau** [comment] 2023-01-02 08:09
Hello,

For those who really need vaadin 23.3.x and apexcharts:

1. Clone Apexchart Github repository
2. Compile using `maven install`
3. Set the version of Apexchart in your Vaadin project to `23.0.1`
4. Start your Vaadin application

I hope the release will be publish soon.

Happy new year and best regards :smiley:

**Comment by higgsja** [comment] 2023-01-02 17:00
You guys are doing a tremendous job. Best wishes in the new year ... and 
may all your resolutions have escape clauses!

a

--


Thanks!
West Point 1976 H-3
	Join us! <https://hlh-tx.com> 	*Mission:* To measurably improve 
investor performance

"We enjoy the comfort of opinion without the discomfort of thought." -- 
J.F. Kennedy

**Comment by amagnolo** [comment] 2023-01-17 16:00
Still no hope to have the fixed version released in Vaadin Directory?

**Comment by WilliamFreau** [comment] 2023-01-25 13:34
Hello,

I think we are many to wait to have the version 23.0.1 of apexcharts working with vaadin 23.3.x.

Do you think release it soon in the Vaadin-Directory?

Best regards

**Comment by appreciated** [comment] 2023-02-13 23:42
Closing as duplicate of #155. Reopen if the issue still occurs with the new version.

**Closed by appreciated** 2023-02-13 23:42 UTC
Labels: bug
